%% M10
descr.coh1.M10.contrast.rawPath=...
  'D:\1.1 cohort1_hsynG7f_11weeks_raw tiff\M12_mecp2pvtd_3mm\RAW\Contrast';
descr.coh1.M10.contrast.firstTiff='Contrast_M12_00001_00001.tif';
descr.coh1.M10.contrast.procPath=...
  'D:\1.2 MeCP2cohort1_11weeks_processed\M10\Contrast_processed';

descr.coh1.M10.DR.rawPath=...
    'XXXX';
descr.coh1.M10.DR.firstTiff='XXXXX';
descr.coh1.M10.DR.procPath=...
    'XXXX';

descr.coh1.M10.OO.rawPath=...
    'XXXX';
descr.coh1.M10.OO.firstTiff='XXXXX';
descr.coh1.M10.OO.procPath=...
    'XXXX';

descr.coh1.M10.OR.rawPath=...
    'XXXX';
descr.coh1.M10.OR.firstTiff='XXXXX';
descr.coh1.M10.OR.procPath=...
    'XXXX';

%etc...



%% M11
descr.coh1.M11.contrast.rawPath=...
    'XXXX';
descr.coh1.M11.contrast.firstTiff='XXXXX';
descr.coh1.M11.contrast.procPath=...
    'XXXX';

descr.coh1.M11.DR.rawPath=...
    'XXXX';
descr.coh1.M11.DR.firstTiff='XXXXX';
descr.coh1.M11.DR.procPath=...
    'XXXX';

descr.coh1.M11.OO.rawPath=...
    'XXXX';
descr.coh1.M11.OO.firstTiff='XXXXX';
descr.coh1.M11.OO.procPath=...
    'XXXX';

descr.coh1.M11.OR.rawPath=...
    'XXXX';
descr.coh1.M11.OR.firstTiff='XXXXX';
descr.coh1.M11.OR.procPath=...
    'XXXX';

%etc...

%% M12 etc....

